### ISSUE TITLE
error decompile

### ISSUE THREAD

**Issue by l13h0ng** [wellrodrig/Whatsapp-Spy#3]
i use APK.Tool.GUI.v3.3.1.2 to decompile
this is capture error, what should i do
thx

[10:21:38] =====[ Decoding ]=====
[10:21:38] 00.000 I: [DECOMPILE] Decompiling ...
[10:21:38]    Input: C:\Users\Administrator\Downloads\Telegram_Version.apk
[10:21:38]  Output: C:\Users\Administrator\Downloads\Telegram_Version
[10:21:38]  Force: true
[10:21:38]  Type: xml
[10:21:38]  ---------------------------- 
[10:21:38] 00.027 I: [DECOMPILE] Loading ...
[10:21:38] ERROR:
[10:21:38] com.reandroid.archive.ArchiveException: Failed to find end record
[10:21:38] 	at com.reandroid.archive.block.EndRecord.findEndRecord(EndRecord.java:89)
[10:21:38] 	at com.reandroid.archive.block.EndRecord.findEndRecord(EndRecord.java:62)
[10:21:38] 	at com.reandroid.archive.model.CentralFileDirectory.visit(CentralFileDirectory.java:48)
[10:21:38] 	at com.reandroid.archive.Archive.<init>(Archive.java:46)
[10:21:38] 	at com.reandroid.archive.ArchiveFile.<init>(ArchiveFile.java:30)
[10:21:38] 	at com.reandroid.archive.ArchiveFile.<init>(ArchiveFile.java:33)
[10:21:38] 	at com.reandroid.apk.ApkModule.loadApkFile(ApkModule.java:1161)
[10:21:38] 	at com.reandroid.apkeditor.decompile.Decompiler.run(Decompiler.java:39)
[10:21:38] 	at com.reandroid.apkeditor.decompile.Decompiler.execute(Decompiler.java:127)
[10:21:38] 	at com.reandroid.apkeditor.Main.execute(Main.java:81)
[10:21:38] 	at com.reandroid.apkeditor.Main.execute(Main.java:64)
[10:21:38] 	at com.reandroid.apkeditor.Main.main(Main.java:36)
[10:21:38] =====[ Error ]=====
[10:21:38] Decompiling failed
[10:21:38] Time started: 10:21:38
[10:21:38] Time elapsed: 00:00

**Comment by xounzz** [comment]
use this command to Decompile apktool d -f -r file.apk then you just edit the token id and chat id then build and the error will not occur because I just experienced it
